// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odebqftzxdpfdwcyvfnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kZWJxZnR6eGRwZmR3Y3l2Zm54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNDM0MTUsImV4cCI6MjA3MzcxOTQxNX0.M354tM8JJNn7hn5c9sJ2U8ymh3sDm5sracbmzXTA0gc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});